Repository CortexFoundation/CortexTheseus, pull requests merged in 2020-07, with the labels that each got.

#634 solution | static libs path added
  consensus/cuckoo/plugins/cpu_helper_for_node.go
  libs/libcpuminer.a
  solution/Makefile
  solution/blake2b.o
  solution/cpuminer.o
  solution/cpuminer.o.temp.o
  solution/cuckoo.o
  solution/siphash.o
Labels: build

#647 go.mod, go.sum | vendor dependencies upgrade
  go.mod
  go.sum
  vendor/github.com/CortexFoundation/torrentfs/README.md
  vendor/github.com/CortexFoundation/torrentfs/params/tracker.go
  vendor/modules.txt
Labels: chore

#551 Increase the test coverage of CortexTheseus
  accounts/abi/bind/base_test.go
  accounts/abi/topics_test.go
  accounts/abi/unpack_test.go
  accounts/errors_test.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/cuckoo/consensus.go
  consensus/cuckoo/cuckoo_faker.go
  core/bench_test.go
  core/block_validator_test.go
  core/blockchain_test.go
  core/chain_makers.go
  core/chain_makers_test.go
  core/cvm.go
  core/rawdb/chain_iterator_test.go
  core/state/state_object_test.go
  core/types/block_test.go
  core/types/receipt_test.go
  core/vm/cvm.go
  ctxc/downloader/downloader_test.go
  ctxc/downloader/testchain_test.go
  ctxc/helper_test.go
  ctxcdb/dbtest/testsuite.go
  ctxcdb/leveldb/leveldb_test.go
  ctxcdb/memorydb/memorydb_test.go
  params/config.go
  rlp/iterator_test.go
Labels: enhancement, in progress, unit test

#648 miner subscribe event split
  miner/miner.go
Labels: mining

#652 go.mod, go.sum | vendor dependencies upgrade
  go.mod
  go.sum
  vendor/github.com/CortexFoundation/torrentfs/README.md
  vendor/github.com/CortexFoundation/torrentfs/go.mod
  vendor/github.com/CortexFoundation/torrentfs/go.sum
  vendor/github.com/allegro/bigcache/v2/iterator.go
  vendor/github.com/allegro/bigcache/v2/queue/bytes_queue.go
  vendor/github.com/allegro/bigcache/v2/shard.go
  vendor/modules.txt
Labels: chore

#658 go.mod, go.sum | vendor dependencies upgrade
  go.mod
  go.sum
  vendor/github.com/CortexFoundation/torrentfs/go.mod
  vendor/github.com/CortexFoundation/torrentfs/go.sum
  vendor/github.com/allegro/bigcache/v2/bigcache.go
  vendor/github.com/allegro/bigcache/v2/shard.go
  vendor/modules.txt
Labels: chore

#656 Keep on increasing the test coverage of CortexTheseus
  common/compiler/test.v.py
  common/compiler/test_bad.v.py
  common/compiler/vyper_test.go
Labels: in progress, unit test

#659 go.mod, go.sum | vendor dependencies upgrade
  go.mod
  go.sum
  vendor/github.com/golang/snappy/AUTHORS
  vendor/github.com/golang/snappy/CONTRIBUTORS
  vendor/github.com/golang/snappy/decode_arm64.s
  vendor/github.com/golang/snappy/decode_asm.go
  vendor/github.com/golang/snappy/decode_other.go
  vendor/github.com/golang/snappy/encode_arm64.s
  vendor/github.com/golang/snappy/encode_asm.go
  vendor/github.com/golang/snappy/encode_other.go
  vendor/golang.org/x/net/dns/dnsmessage/message.go
  vendor/modules.txt
Labels: chore

#671 ctxc/gasprice/gasprice test
  ctxc/gasprice/gasprice.go
  ctxc/gasprice/gasprice_test.go
Labels: unit test

#674 go.mod, go.sum | vendor dependencies upgrade
  go.mod
  go.sum
  vendor/github.com/CortexFoundation/torrentfs/README.md
  vendor/github.com/CortexFoundation/torrentfs/default.go
  vendor/github.com/CortexFoundation/torrentfs/go.mod
  vendor/github.com/CortexFoundation/torrentfs/go.sum
  vendor/github.com/CortexFoundation/torrentfs/handler.go
  vendor/github.com/CortexFoundation/torrentfs/params/chain.go
  vendor/github.com/anacrolix/torrent/go.mod
  vendor/github.com/anacrolix/torrent/go.sum
  vendor/github.com/anacrolix/torrent/webseed-peer.go
  vendor/modules.txt
Labels: chore

#690 Embedded-storage by using torrentfs
  cmd/cortex/config.go
  cmd/cortex/cvm.go
  cmd/utils/flags.go
  core/state_transition.go
  core/vm/cvm.go
  core/vm/interpreter.go
  ctxc/handler.go
  go.mod
  go.sum
  inference/synapse/local_infer.go
  inference/synapse/synapse.go
  vendor/github.com/CortexFoundation/torrentfs/chaindb.go
  vendor/github.com/CortexFoundation/torrentfs/fs.go
  vendor/github.com/CortexFoundation/torrentfs/handler.go
  vendor/github.com/CortexFoundation/torrentfs/interfaces.go
  vendor/github.com/CortexFoundation/torrentfs/params/chain.go
  vendor/github.com/CortexFoundation/torrentfs/sync.go
  vendor/modules.txt
Labels: enhancement
